apiVersion: apps/v1
kind: Deployment
metadata:
  name: solicite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solicite-service
  template:
    metadata:
      labels:
        app: solicite-service
    spec:
      containers:
        - name: solicite-service
          image: cledsonjr/solicite-service:latest
